export const ADD_FILTER_STOPS    = "ADD_FILTER_STOPS"
export const TOGGLE_FILTER_STOPS    = "TOGGLE_FILTER_STOPS"

export const ADD_FILTERS_TICKETS    = "ADD_FILTERS_TICKETS"
export const TOGGLE_FILTER_TICKETS    = "TOGGLE_FILTER_TICKETS"

export const START_FILL_INITIAL_LIST = "START_FILL_INITIAL_LIST"
export const ADD_PACK_INITIAL_LIST   = "ADD_PACK_INITIAL_LIST"
export const STOP_FILL_INITIAL_LIST  = "STOP_FILL_INITIAL_LIST"

export const ADD_ERROR_MESSAGE="ADD_ERROR_MESSAGE"
export const CLEAR_ERROR_MESSAGE="CLEAR_ERROR_MESSAGE"

export const ADD_COUNT_LIMIT_TICKETS="ADD_COUNT_LIMIT_TICKETS"

export const LOAD_FILTERED_LIST_TICKETS = "LOAD_FILTERED_LIST_TICKETS"
export const SORT_FILTERED_LIST_TICKETS = "SORT_FILTERED_LIST_TICKETS"
export const INITIAL_LIMIT_TICKETS = "INITIAL_LIMIT_TICKETS"